name = "gnt-dev"
compatibility_date = "2025-04-20"

[assets]
directory = "./dist"

# 👇 Build output from Vite
[build]
command = "npm run build"
upload.dir = "./dist"  # where Vite builds to
upload.format = "directory"

